name: MongoDB Run Tests
on: [push, pull_request]

jobs:
  test:
    name: Server Tests
    strategy:
      matrix:
        dc: [dmd-latest, ldc-latest]
        mongodb-version: [3.6, 4.0, 4.2, 4.4, 5.0] # can't test 6.0 yet since the op_query deprecated

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Install D compiler
      uses: mihails-strasuns/setup-dlang@v1
      with:
        compiler: ${{matrix.dc}}
    - name: Run tests
      run: dub test
    - name: Run server tests
      run: ./ci.sh
