name: MongoDB Run Tests
on: [push, pull_request]

jobs:
  test:
    name: Server Tests
    strategy:
      fail-fast: false
      matrix:
        dc: [dmd-latest, ldc-latest]
        mongodb-version: [3.6, 4.0, 4.2, 4.4, 5.0] # can't test 6.0 yet since the op_query deprecated

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Install mongosh
      run: |
        wget -qO- https://www.mongodb.org/static/pgp/server-8.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-8.0.asc
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-mongosh
        mongosh --version
    - name: Install mongodb-database-tools
      run: |
        wget -q -O mongodb-tools.deb https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2404-x86_64-100.14.1.deb
        sudo apt-get install ./mongodb-tools.deb
    - name: Install D compiler
      uses: mihails-strasuns/setup-dlang@v1
      with:
        compiler: ${{matrix.dc}}
    - name: Run tests
      run: dub test
    - name: Run server tests
      run: ./ci.sh
